version: "3.9"
services:
  nftables:
    build: 
      context: .
      dockerfile: nftables-dockerfile
    networks:
      network:
        ipv4_address: 10.5.0.2

  nmap:
    build: 
      context: .
      dockerfile: nmap-dockerfile
    networks:
      network:
        ipv4_address: 10.5.0.3
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      network:
        ipv4_address: 10.5.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1